- name: "Install python3"
  hosts: localhost
  connection: local
  become: yes

  tasks:
    
    - apt:
        update_cache: yes
    
    - apt:
        upgrade: dist

    - apt:
        name: python3-docker
        state: present
    
    - apt:
        name: python3-pip
        state: present