- name: "Nextcloud playbook"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - docker_container:
        restart: yes
        restart_policy: always
        name: nextcloud
        image: ownyourbits/nextcloudpi
        pull: yes
        volumes:
          - '/storage/cloud_data:/data'
        env:
          VIRTUAL_HOST: '{{cloud_url}}'
          # LETSENCRYPT_HOST: '{{cloud_url}}'
          # LETSENCRYPT_EMAIL: 'e@e.e'
        networks:
          - name: nginx-proxy
      tags: "container"        