- name: "Nextcloud playbook"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - docker_container:
        restart: yes
        restart_policy: always
        name: nextcloud
        image: ownyourbits/nextcloudpi
        pull: yes
        volumes:
          - '{{storage_location}}:/data'
        env:
          VIRTUAL_HOST: 'cloud.home'
          LETSENCRYPT_HOST: 'cloud.home'
          LETSENCRYPT_EMAIL: 'psa9710@gmail.com'
        networks:
          - name: nginx-proxy
      tags: "container"        